apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  name: random-experiment
  namespace: ''
spec:
  maxTrialCount: 24
  parallelTrialCount: 3
  maxFailedTrialCount: 3
  resumePolicy: Never
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: val_acc
    additionalMetricNames:
      - val_loss
  algorithm:
    algorithmName: random
    algorithmSettings: []
  parameters:
    - name: learning_rate
      parameterType: double
      feasibleSpace:
        min: '0.01'
        max: '0.1'
        step: '0.01'
    - name: dropout
      parameterType: double
      feasibleSpace:
        min: '0.1'
        max: '0.3'
    - name: opt
      parameterType: int
      feasibleSpace:
        min: '0'
        max: '1'
  metricsCollectorSpec:
    source:
      fileSystemPath:
        path: /var/log/katib/metrics.log
        kind: File
  trialTemplate:
    primaryContainerName: training-container
    successCondition: status.conditions.#(type=="Complete")#|#(status=="True")#
    failureCondition: status.conditions.#(type=="Failed")#|#(status=="True")#
    retain: True      # log 확인 가능
    trialParameters:
      - name: learning_rate
        description: Learning Rate for modeling training
        reference: learning_rate
      - name: dropout
        description: dropout rate
        reference: dropout
      - name: opt
        description: Optimizer for modeling training
        reference: opt
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          metadata:
            annotations:
              sidecar.istio.io/inject: "false"
          spec:
            containers:
              - name: training-container
                image: seokii/mnist-katib-random:0.0.4
                # image: docker.io/nevret/nevret-katib-mnist:0.1
                command:
                  - "python"
                  - "/mnist-katib-random.py"
                  - "--learning_rate=${trialParameters.learning_rate}"
                  - "--dropout=${trialParameters.dropout}"
                  - "--opt=${trialParameters.opt}"
            restartPolicy: Never